// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtoECommerce.Infrastructure;

#nullable disable

namespace MtoECommerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250711120421_littlemissinimagesjpgtojpeg")]
    partial class littlemissinimagesjpgtojpeg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MtoECommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shirts",
                            Slug = "shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dress",
                            Slug = "dress"
                        });
                });

            modelBuilder.Entity("MtoECommerce.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "This is the home page",
                            Order = 0,
                            Slug = "home",
                            Title = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Body = "This is the about page",
                            Order = 0,
                            Slug = "about",
                            Title = "About"
                        },
                        new
                        {
                            Id = 3,
                            Body = "This is the services page",
                            Order = 0,
                            Slug = "services",
                            Title = "Services"
                        },
                        new
                        {
                            Id = 4,
                            Body = "This is the contact page",
                            Order = 0,
                            Slug = "contact",
                            Title = "Contact"
                        });
                });

            modelBuilder.Entity("MtoECommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A Nice Blue Polo Shirt for Men",
                            Image = "PoloShirt.jpeg",
                            Name = "Polo Shirt",
                            Price = 22.79m,
                            Slug = "polo-shirt"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Black Strappy Volume-Hem Midi Dress",
                            Image = "BlackDress1.jpeg",
                            Name = "Parina Black Dress",
                            Price = 127.99m,
                            Slug = "parina-black-dress"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Lemon Asymmetric Neckline High-Split Maxi Dress",
                            Image = "LemonDress1.jpeg",
                            Name = "Beth Lemon Dress",
                            Price = 132.69m,
                            Slug = "beth-lemon-dress"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Navy & White Stripe Pure Linen Slim Shirt – Button Down Collar",
                            Image = "StripyShirt1.jpeg",
                            Name = "Navy & White Stripe Shirt",
                            Price = 75.32m,
                            Slug = "stripe-shirt"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Pink Strappy Volume-Hem Midi Dress",
                            Image = "PinkDress1.jpeg",
                            Name = "Parina Pink Dress",
                            Price = 110.89m,
                            Slug = "parina-pink-dress"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Crafted from 100% cotton sateen and cut for a tailored fit. With a classic cutaway collar, mitred cuffs, and a slight sheen from the lustrous fabric, these are the ultimate statement shirts. This shirt features accents of our Name Of The Rose Print.",
                            Image = "RedShirt1.jpeg",
                            Name = "Burgundy Sateen Shirt",
                            Price = 106.14m,
                            Slug = "burgundy-sateen-shirt"
                        });
                });

            modelBuilder.Entity("MtoECommerce.Models.Product", b =>
                {
                    b.HasOne("MtoECommerce.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
